#!/usr/bin/env bash

pip3 install /opt/storage_piCopilot-wifi/packetEssentials-1.8.8.tar.gz
pip3 install /opt/storage_piCopilot-wifi/pbkdf2-1.3.tar.gz
pip3 install /opt/storage_piCopilot-wifi/pyDot11-2.3.4.tar.gz
pip3 install /opt/storage_piCopilot-wifi/pycryptodomex-3.4.5.tar.gz
pip3 install /opt/storage_piCopilot-wifi/rc4-0.2.tar.gz
pip3 install /opt/storage_piCopilot-wifi/scapy-2.4.5.tar.gz
pip3 install /opt/storage_piCopilot-wifi/easy-thread-1.0.8.tar.gz
pip3 install /opt/storage_piCopilot-wifi/quickset-0.6.8.tar.gz
