#!/usr/bin/env bash

pip3 uninstall packetEssentials -y
pip3 uninstall pbkdf2 -y
pip3 uninstall pyDot11 -y
pip3 uninstall pycryptodomex -y
pip3 uninstall rc4 -y
pip3 uninstall scapy -y
pip3 uninstall easy-thread -y
pip3 uninstall quickset -y
