#!/usr/bin/env bash

## chown for postgres
mkdir -p /opt/piCopilot-idrop/visuals
mkdir -p /opt/piCopilot-idrop/logs
chown -R postgres /opt/piCopilot-idrop/logs

## Start supervisor daemon
systemctl start supervisor
systemctl enable supervisor

## Ensure postgresql running
systemctl enable postgresql
systemctl start postgresql
