#!/bin/sh

### BEGIN INIT INFO
# Provides:          copilotWifi.sh
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

case "$1" in
  start)
    /usr/bin/copilotWifi.sh &
    ;;
  stop)
    pkill -f /usr/bin/copilotWifi.sh
    ;;
  *)
    echo "Usage: /etc/init.d/copilotWifiDaemon {start|stop}"
    exit 1
    ;;
esac

exit 0
