#!/bin/sh

### BEGIN INIT INFO
# Provides:          copilotSystem.py
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

case "$1" in
  start)
    /usr/bin/copilotSystem.py &
    ;;
  stop)
    pkill -f /usr/bin/copilotSystem.py
    ;;
  *)
    echo "Usage: /etc/init.d/copilotSystemDaemon {start|stop}"
    exit 1
    ;;
esac

exit 0

