#!/usr/bin/env bash

## SYS it up
update-rc.d copilotSystemDaemon defaults
update-rc.d copilotWifiDaemon defaults
service copilotSystemDaemon start

## unmask hostapd
systemctl unmask hostapd.service

## Disable again -- Bug fix?
systemctl disable hostapd

## GPS
pip3 install /opt/storage_piCopilot/gpsd-py3-0.3.0.tar.gz
