#!/usr/bin/env bash

## SYS it up
update-rc.d copilotSystemDaemon defaults
update-rc.d copilotWifiDaemon defaults
service copilotSystemDaemon start

## unmask hostapd && disable
systemctl unmask hostapd.service
systemctl disable hostapd

## GPS
pip3 install /opt/storage_piCopilot/gpsd-py3-0.3.0.tar.gz --break-system-packages

## Create empty wpa_supplicant
touch /etc/wpa_supplicant/wpa_supplicant.conf
mkdir /etc/network/interfaces.d
touch /etc/network/interfaces.d/wlan0
touch /etc/network/interfaces.d/eth0

## Allow ubuntu to modify via ssh command
chown ubuntu /etc/hostapd/hostapd.conf
chmod 0664 /etc/hostapd/hostapd.conf
chown ubuntu /etc/wpa_supplicant/wpa_supplicant.conf
chmod 0664 /etc/wpa_supplicant/wpa_supplicant.conf
chown ubuntu /etc/hostapd/hostapd.conf
chmod 0664 /etc/hostapd/hostapd.conf
chown ubuntu /etc/dnsmasq.conf
chmod 0664 /etc/dnsmasq.conf
chown ubuntu /etc/network/interfaces.d/wlan0
chmod 0664 /etc/network/interfaces.d/wlan0
chown ubuntu /etc/network/interfaces.d/eth0
chmod 0664 /etc/network/interfaces.d/eth0
chown ubuntu /usr/bin/copilotDhcp.sh
chmod 0755 /usr/bin/copilotDhcp.sh
